name: Update README Analytics

on:
  push:
    branches: [ main, develop ]
  schedule:
    - cron: '0 9 * * *'  # Every day at 9 AM
  workflow_dispatch:  # Manual trigger

jobs:
  update-readme:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all history for accurate stats
    
    - name: Update README Analytics
      run: |
        chmod +x scripts/update_readme_analytics.sh
        ./scripts/update_readme_analytics.sh
    
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "📊 Update project analytics [automated]"
          git push
        fi
